name: style_widget
description: A concept for decorator syntax without the namespace leakage
version: 0.0.1
repository: https://github.com/lukepighetti/style_widget/

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
